---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tdarr-server
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: haveagitgat/tdarr
      tag: 2.17.01
      pullPolicy: IfNotPresent

    env:
      TZ: ${TIMEZONE}
      PUID: 1030
      PGID: 100

    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: material-symbols:switch-video
        hosts:
          - host: &host "tdarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
      capabilities:
        add:
          - CHOWN

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: tdarr-config
        mountPath: /app/configs
      data:
        enabled: true
        type: pvc
        existingClaim: tdarr-data
        mountPath: /app/server
      cache:
        enabled: true
        type: pvc
        existingClaim: tdarr-cache
      media:
        enabled: true
        type: pvc
        existingClaim: data

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
