---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-data
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 15Gi

  storageClassName: ceph-block
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tdarr-cache
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
spec:
  storageClassName: tdarr-cache
  capacity:
    storage: 1Mi # doesn't matter
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: "${SECRET_NAS_HOST}"
    path: "${SECRET_NAS_PATH}/tdarr-cache"
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tdarr-cache
  resources:
    requests:
      storage: 1Mi # doesn't matter
