---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: immich-server

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.88.2@sha256:134b6d16b76acd2b6a6ee43c6866668c1c00c33fb3c989bbae5ad867acc2f71b

    env:
      DB_HOSTNAME: "immich-db-rw.default.svc.cluster.local"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap

    service:
      main:
        ports:
          http:
            port: 3003

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      library:
        enabled: true
        type: pvc
        existingClaim: photos
        mountPath: /usr/src/app/upload
      cache:
        enabled: true
        type: emptyDir
      geocoding-dump:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/.reverse-geocoding-dump
      transformers-cache:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/.transformers_cache

    resources:
      requests:
        cpu: 5m
        memory: 274M

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
