---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-microservices
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: immich-server
    - name: immich-typesense

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.72.2@sha256:d306708a090a814d6e3660e7fd372403b92600a1624b398ca2c00e8f3eaeaa1a

    command: /bin/sh
    args:
      - ./start-microservices.sh

    env:
      DB_HOSTNAME: "immich-db-rw.default.svc.cluster.local"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap

    service:
      main:
        enabled: false

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      library:
        enabled: true
        type: pvc
        existingClaim: photos
        mountPath: /usr/src/app/upload
      geocoding-dump:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/.reverse-geocoding-dump
      geoname-dump:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/node_modules/local-reverse-geocoder/geonames_dump
      transformers-cache:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/.transformers_cache

    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        cpu: 5m
        memory: 277M
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
