---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/larivierec/bitwarden-cli
      tag: latest
    podAnnotations:
      configmap.reloader.stakater.com/reload: bitwarden-cli
    envFrom:
      - secretRef:
          name: bitwarden-cli
    service:
      main:
        ports:
          http:
            port: 8087
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              [
                "sh",
                "-c",
                "curl -X POST -s http://127.0.0.1:8087/sync | jq -e '.success == true'",
              ]
      readiness:
        enabled: false
    resources:
      requests:
        cpu: 34m
        memory: 247M
      limits:
        memory: 1241M
