---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: redis
      tag: 7.2.4-alpine
    controller:
      type: deployment
    service:
      main:
        ports:
          http:
            port: 6379
    command:
      - sh
    args:
      - -c
      - >-
        redis-server
    persistence:
      healthcheck:
        enabled: true
        type: custom
        mountPath: /health
        volumeSpec:
          configMap:
            name: redis-healthcheck
            defaultMode: 0755
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - sh
              - -c
              - /health/ping_liveness.sh 5
          initialDelaySeconds: 5
          timeoutSeconds: 6
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      readiness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - sh
              - -c
              - /health/ping_readiness.sh 1
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 5

    resources:
      requests:
        cpu: 10m
        memory: 475M
      limits:
        memory: 1219M

    env:
      REDIS_PORT: "6379"
