---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-auto-languages
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: plex-auto-languages-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: 4fb30ad8-72d5-435b-8010-a85af537b102
        property: token
