---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-07-11T21-29-34Z

    env:
      TZ: "${TIMEZONE}"
      MINIO_UPDATE: "off"
      MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      MINIO_PROMETHEUS_JOB_ID: minio
      MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
      MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
      MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}

    envFrom:
      - secretRef:
          name: minio-secret

    args: ["server", "/data", "--console-address", ":9001"]

    service:
      main:
        enabled: true
        ports:
          http:
            port: &console-port 9001
          api:
            enabled: true
            port: &api-port 9000

    serviceMonitor:
      main:
        enabled: false
        endpoints:
          - port: api
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /minio/health/live
            port: *api-port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:pail
        hosts:
          - host: &console-host "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
                service:
                  port: *console-port
        tls:
          - hosts:
              - *console-host
      s3:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &api-host "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *api-port
        tls:
          - hosts:
              - *api-host

    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: minio-nfs

    resources:
      requests:
        memory: 295M
        cpu: 10m
      limits:
        memory: 750M
