---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudnative-pg
  namespace: databases
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      tag: 1.21.0

    resources:
      requests:
        cpu: 10m
        memory: 163M
      limits:
        memory: 418M
