---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich-server
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.100.0@sha256:d603fd34d587cbf0c99442bb44da395450157d5eb7dec40d2d1d16f2cfdb988b

    command: /bin/sh
    args:
      - ./start-server.sh

    env:
      DB_HOSTNAME: "immich-db-rw.default.svc.cluster.local"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password
      SERVER_PORT: &port 3001

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$client_ip"
          hajimari.io/appName: Immich
          hajimari.io/icon: heroicons:photo
        hosts:
          - host: &host "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      library:
        enabled: true
        type: pvc
        existingClaim: photos
        mountPath: /usr/src/app/upload
      transformers-cache:
        enabled: true
        type: emptyDir
        mountPath: /usr/src/app/.transformers_cache

    resources:
      requests:
        cpu: 5m
        memory: 140M

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
