data_dir: /vector-data-dir

# Sources
sources:
  kubernetes_logs:
    type: kubernetes_logs
    use_apiserver_cache: true
    pod_annotation_fields:
      container_image: container_image
      container_name: container_name
      pod_labels: pod_labels
      pod_name: pod_name
      pod_annotations: ""
    namespace_annotation_fields:
      namespace_labels: ""
    node_annotation_fields:
      node_labels: ""
  journald_logs:
    type: journald
    journal_directory: /var/log/journal

# Sinks
sinks:
  kubernetes_sink:
    type: vector
    compression: true
    inputs:
      - kubernetes_logs
    address: vector-aggregator.monitoring.svc.cluster.local:6000
    version: "2"

  journald_sink:
    type: vector
    compression: true
    version: "2"
    address: vector-aggregator.monitoring.svc.cluster.local:6001
    inputs:
      - journald_logs

