---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.100
  share: /volume2/k8s-data
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
