---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: add-refresh-interval-to-external-secrets
  annotations:
    policies.kyverno.io/title: Add RefreshInterval to ExternalSecrets
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: ExternalSecret
    policies.kyverno.io/description: >-
      This policy adds a refreshInterval of 1m to ExternalSecrets

spec:
  mutateExistingOnPolicyUpdate: true

  rules:
  - name: refresh-interval
    match:
      any:
      - resources:
          kinds:
            - ExternalSecret

    mutate:
      targets:
        - apiVersion: external-secrets.io/v1beta1
          kind: ExternalSecret

      patchStrategicMerge:
        spec:
          refreshInterval: "1m"
