---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: enable-goldilock-on-all-namespaces
  annotations:
    policies.kyverno.io/title: Enables Goldilocks on all namespaces
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Namespace
    policies.kyverno.io/description: >-
      This policy enables Goldilocks on all namespaces

spec:
  mutateExistingOnPolicyUpdate: true

  rules:
  - name: enable-goldilocks
    match:
      any:
      - resources:
          kinds:
            - Namespace

    mutate:
      targets:
        - apiVersion: v1
          kind: Namespace

      patchStrategicMerge:
        metadata:
          labels:
            goldilocks.fairwinds.com/enabled: "true"
