---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: recyclarr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: '{{ index . "radarr-api-key" }}'
        SONARR_API_KEY: '{{ index . "sonarr-api-key" }}'
  data:
    - secretKey: radarr-api-key
      remoteRef:
        key: 1ebb772c-5767-414f-a869-79e24b6d8938
        property: api-key
    - secretKey: sonarr-api-key
      remoteRef:
        key: 4294795c-a50a-4cd6-a994-def34f1be71c
        property: api-key
