---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    envFrom:
      - secretRef:
          name: recyclarr-secret

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 6.0.2@sha256:02add40feae0569401b5020528e06419b47046723d0bb4bef1e82325e9eefdad

    podAnnotations:
      setGateway: "true"

    persistence:
      config:
        enabled: true
        existingClaim: recyclarr-config
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        readOnly: true

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: OnRootMismatch

    resources:
      requests:
        cpu: 10m
        memory: 37M
      limits:
        memory: 94M

    service:
      main:
        enabled: false
