---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actual
  namespace: finance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: actual-secret
    creationPolicy: Owner
  data:
    - secretKey: ACTUAL_NORDIGEN_SECRET_ID
      remoteRef:
        key: 4e76974e-e344-4fb4-903f-eb0db78cefe2
        property: nordigen-secret-id
    - secretKey: ACTUAL_NORDIGEN_SECRET_KEY
      remoteRef:
        key: 4e76974e-e344-4fb4-903f-eb0db78cefe2
        property: nordigen-secret-key
