---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: data
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  storageClassName: data
  capacity:
    storage: 1Mi # doesn't matter
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NAS_HOST}"
    path: "${SECRET_MEDIA_PATH}"
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: data
  resources:
    requests:
      storage: 1Mi # doesn't matter
