---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./volsync.yaml
configMapGenerator:
  - name: bazarr-scripts
    files:
      - post-process.sh=./scripts/post-process.sh
configurations:
  - ./patches/kustomizeconfig.yaml
