apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:lfca2uhfjnY8YqlGcdNd5VFhxK+41/Pm7anZIB95kVP6WwxrnUCg+w==,iv:AxsQVwun+rjwoy59ZCo93KnYHkvsiYcKUBIUhECoZSM=,tag:5QwROJog7RfOl5MTZghkYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1huwtfh57f93ceeav3k9xdmmnj90yzdaa05szskg2hat2rrq00yesyl2y5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UlhZQU1Vc1QrTko4eXY0
            b1NRVjZGYnhGZjI5WjQwMG81a3ZEYklXdVd3Ck8xNGlmbkd6bkZ1SnhXNzFSQlFw
            cEE2d3crY0o5Lzc1Mk1qMldkWkdoZGcKLS0tIGErdVFsczJUM0g1ak40dEozajJl
            a0lzZVhqOXBsRk1Ud1lqZDFXUkdkMlkKCXXJtAR+JMlBq/Eqv0IUPWCACw65Vqz4
            vHrL9dFY2mNagdQgzbEPka19ywAhyLpIbHhG9EsgV/ApfX+2dO1sfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T22:56:09Z"
    mac: ENC[AES256_GCM,data:yCsOvhRnE6FfRbiJTHsvhR1sAFo9+1LkvKV6LGUr4aDCTVAA8NK2DBIJLYefo4x6t6eea+At/27l1QH7AbwZjMkOF6z3bjIdIGRnrlEJL5zhX+91PEp69HesDjacO52UU80HfdUOSsrIdKlfyyr0y5CwXzsJO94yUAttIf794po=,iv:Cu2hQ71Re8ki4mjAF9qlXKujx5JSqjAMmV552YlMUoA=,tag:gKRStYRGToz/19WMHjEcXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
