---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-immich-redis
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/default/immich/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-immich
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/default/immich/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-immich-redis
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-external-secrets-bitwarden
    - name: cluster-apps-rook-ceph-cluster
