---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: 4676e84c-82bc-4601-8591-8c4e0cd8dc18
        property: api-key
