---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 7.2.4@sha256:3134997edb04277814aa51a4175a588d45eb4299272f8eff2307bbf8b39e4d43

    env:
      REDIS_REPLICATION_MODE: master

    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379

    resources:
      requests:
        cpu: 5m
        memory: 10M
      limits:
        memory: 10M
