---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-secret
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: actions-runner-controller-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: b7017e92-45e7-47fe-97c2-914dcff4191e
        property: token
    - secretKey: url
      remoteRef:
        key: b7017e92-45e7-47fe-97c2-914dcff4191e
        property: url
