---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-terraform
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: "ssh://git@github.com/arthurgeek/home-k8s.git"
  secretRef:
    name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include terraform directory
    !/terraform
