---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 12h
  approvePlan: auto
  cloud:
    organization: arthurgeek
    hostname: app.terraform.io
    workspaces:
      name: arpa-home-minio
  cliConfigSecretRef:
    name: tf-cli-config
  path: ./terraform/minio
  sourceRef:
    kind: GitRepository
    name: home-terraform
    namespace: flux-system
  tfstate:
    forceUnlock: auto
  varsFrom:
    - kind: Secret
      name: bitwarden-cli
