apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
    namespace: kube-system
stringData:
    bw_server: ENC[AES256_GCM,data:6O2rLnHjK7Aq/K9n93jdifkLNMCOaxc4E6w=,iv:T4PUrd+u+1++RrQ4dXTVuQrppR0NbxoqsmAowq10J0A=,tag:vHuCcmmgoiiWaNh17xw8jw==,type:str]
    bw_email: ENC[AES256_GCM,data:Z1biv6emixBMdOxxRMdHBoPYQ/Lb,iv:Gde+d9xA0HEw2qyjOkeux72zatArcxJ2vxRsPv4QItw=,tag:zn5o/KNbPSHYZHJmNK9Zgw==,type:str]
    bw_client_id: ENC[AES256_GCM,data:hktNL4RsLOLrnb4iMsQ7fjtTyU01fI9B23VpqyvR7/eCUV2rCqJykr4=,iv:dNZT+E6scuSvlKVdS1FrEns08zt9FgxjSZQHEB/0cug=,tag:SdcJ8C8jhGFkjdrpcmKhpA==,type:str]
    bw_client_secret: ENC[AES256_GCM,data:iopNzxYEf1q8sAHFmZWN5DV3VEsNEJpJR8W+fG76,iv:uTJJdHFQ8RQCECIkgLDMhK/4pzWJyJUOn9WWvGGQDZc=,tag:stNwRff0250iVQ6cAZhMXA==,type:str]
    bw_password: ENC[AES256_GCM,data:7luAaCq3ekqSL3bvxBP4LaZMlAyOz8lX3XfJU+nPGmBYXx/v0725UgAu9xg=,iv:/TOu1l8FECU7b+MOmNbVSGLba6q8NrDuRCwnhTmHCMQ=,tag:TZLRPKZxueBSyr0H6+9vLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1huwtfh57f93ceeav3k9xdmmnj90yzdaa05szskg2hat2rrq00yesyl2y5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5b0dpcHgrVFFWcGMzKzVq
            b21oczFDNzBOVDhkTU16RnhmZkdPS2thVnhJCkhNL0hCYURDK1pzUHpDV1FvODF2
            Y0l0dElLMlJCV3JGMzI5eEpUQ0djZFkKLS0tIG4wMUZIV1J1Rk1qR096MUpxSWcv
            VzJ0VEhyL2luSGJnTHZicG5yN2V3QzQK7eLlnh5Atvtp40KL11I1sGtbEtzz0QR6
            IlGV2XM2u3JfRjo1IaGToqA59Ia7moTJDV2Gi5e3hhy3FlFbsUSkgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-19T00:45:21Z"
    mac: ENC[AES256_GCM,data:cNVvj8zQd3GSdnAUGwEY/g5E5DSfaUAyOjzfq4Vby+6k8Rn8h69oja7enPNagAwJ3tmpQWo84zKtR4yTfcUziPifPyCzvM0pIEUOocIAawae8cqaA4kS468MbVzjLXkLsV3AdRMh+8/V+VbPIP/bQ0meJsc+laPIbX4EqGRyt+M=,iv:qq1S8q2xRSKyQWM0BUHQO1b40cCevnEDD1Bl3sn8ar0=,tag:zgkhT9xvjaXiJMyLo1E9LA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
