---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vector-aggregator
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/vector/aggregator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-loki
    - name: cluster-apps-external-secrets-bitwarden
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vector-agent
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/vector/agent"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-vector-aggregator
