---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: sonarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: 4294795c-a50a-4cd6-a994-def34f1be71c
        property: api-key
