---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sonarr
      tag: 4.0.2.1183@sha256:42ba5af9b0ea20f4db4622991e0f1657be02c6e8747872c652fdac193c097b25

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"

    env:
      TZ: ${TIMEZONE}
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__API_KEY:
        valueFrom:
          secretKeyRef:
            name: sonarr-secret
            key: api-key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      data:
        enabled: true
        type: pvc
        existingClaim: data

    resources:
      requests:
        cpu: 10m
        memory: 248M
      limits:
        memory: 638M
