---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      tag: v3.3.12

    env:
      TZ: ${TIMEZONE}
      LOG_LEVEL: info

    podAnnotations:
      setGateway: "true"

    service:
      main:
        ports:
          http:
            port: 8191

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
