---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: cluster-user-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: &key 73c5d840-f9a9-4f06-b0b1-99d3345e9a42
        property: username
    - secretKey: password
      remoteRef:
        key: *key
        property: password
