apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:GPfgf7JBxk8vtWvQNw3gZHwChstbUCx/IBxn5rLX4FAFQncQ7nExMjJJ4js9+fs4JdJaVIbg0YYHTGDa,iv:xvnkSVfzQH+UXveWocEzP3DDwa5itDuKpMyTE6cXn/k=,tag:HAjwHjvVCuluHb3lG1GLPw==,type:str]
    username: ENC[AES256_GCM,data:g6j1C5k=,iv:sv5Kv429zjBLyCjpBvCNiA4K92s0gE08zGW3pSsC0UM=,tag:RtOEdR0MHICwwbNvPe4scQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1huwtfh57f93ceeav3k9xdmmnj90yzdaa05szskg2hat2rrq00yesyl2y5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY3BwUktCNU5XUmkzMzh5
            dEZPMFVMbUNlSG1rSXdvOTQxSjhHMmdDNTFrClkvZUQyS2M4ZzN5YWlsVWVQUFY5
            bG1hWkNHQzNZc2JmSENvNG85eFdlS00KLS0tIDNpZEt3R24zS3B6ckQwZjhPTjlt
            Z1FmeHZTaXZZQVJ1Vjd0SXo1S0x3YkkKNhYMkFlk3yEE8QA5VBkdAOp+447nArg8
            3ExI3loyEnClM5pmkjEeroMKe71epFQqSo3xbh8qRTieN0QG20vhJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T22:56:22Z"
    mac: ENC[AES256_GCM,data:8eI1XZ1CYV86sr02JM3tnSuGxkNRxaKsFVn+6DtFWH2xrJeGP7Hi8dDxf3XxprFsPvbHFfRuIHS6dj58vRwRGCpe+wL/aPOlOckkoeO9PDmjo8OD0UMqsPuL9rvNXWsfvcTnCRhzDXYYnCO2uBdPfyvVJNInqatrPnXP5//14hM=,iv:etVR16oH1PcjkQxzI7TL//iuLfsB+dqayjH1W29XS3E=,tag:b24CSMFxEIQlhyrW7EQesA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
