---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-recyclarr
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/downloads/recyclarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-pod-gateway-downloads
    - name: cluster-apps-external-secrets-bitwarden
    - name: cluster-apps-rook-ceph-cluster
