---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: radarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: 1ebb772c-5767-414f-a869-79e24b6d8938
        property: api-key
