---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-volsync
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/backup/volsync/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-snapshot-controller
  wait: false # no flux ks dependents
  timeout: 2m
