---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-subnet
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: tailscale
    serviceAccount:
      name: tailscale
    image:
      repository: ghcr.io/tailscale/tailscale
      tag: v1.44.0
    podAnnotations:
      configmap.reloader.stakater.com/reload: tailscale-auth
    env:
      TZ: ${TIMEZONE}
      NO_AUTOUPDATE: "true"
      TS_KUBE_SECRET: "tailscale-auth"
      SA_NAME: tailscale
      TS_USERSPACE: "true"
      TS_ROUTES: "192.168.1.0/24"
      TS_EXTRA_ARGS: "--advertise-exit-node"
    envFrom:
      - secretRef:
          name: tailscale-auth
    service:
      main:
        ports:
          http:
            port: 45387
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    ingress:
      main:
        enabled: false
