---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app immich-web
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  dependsOn:
    - name: immich-server

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.82.1@sha256:b59ec80d45a9395f020c312868abd08eafbfe3594e83955d7e566096309f0f2f

    command: /bin/sh
    args:
      - ./entrypoint.sh

    env:
      DB_HOSTNAME: "immich-db-rw.default.svc.cluster.local"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/icon: heroicons:photo
        hosts:
          - host: &host "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      library:
        enabled: true
        type: pvc
        existingClaim: photos
        mountPath: /usr/src/app/upload

    resources:
      requests:
        cpu: 5m
        memory: 64M

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
