---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: downloads-gateway-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: &key 2b1c7432-57a5-434b-aed2-65a132f82dad
        property: wireguard-private-key
    - secretKey: SERVER_HOSTNAMES
      remoteRef:
        key: *key
        property: hostnames
