---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: loki
        S3_BUCKET_HOST: minio.storage.svc.cluster.local:9000
        S3_BUCKET_REGION: us-east-1
        S3_ACCESS_KEY: "{{ .minio_loki_access_key }}"
        S3_SECRET_KEY: "{{ .minio_loki_secret_key }}"
  data:
    - secretKey: minio_loki_access_key
      remoteRef:
        key: &key 495ba20c-1f87-403c-88f5-36f9c39b56fa
        property: username
    - secretKey: minio_loki_secret_key
      remoteRef:
        key: *key
        property: password
