---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ index . "account-tag" }}",
            "TunnelSecret": "{{ index . "tunnel-secret" }}",
            "TunnelID": "{{ index . "tunnel-id" }}"
          }
  data:
    - secretKey: account-tag
      remoteRef:
        key: &key 2a4992c1-414d-4f5e-bf6b-caf5869ef5eb
        property: account-tag
    - secretKey: tunnel-secret
      remoteRef:
        key: *key
        property: tunnel-secret
    - secretKey: tunnel-id
      remoteRef:
        key: *key
        property: tunnel-id
