apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:96OQqrtaHEE8BWO2R0mWNSP5YtQ4zwws0wBaAqW9LHkV0rNQ,iv:gV4QnYABNrEG75fG5PAIObujbjqtyg+Xl1aBFP9y8oA=,tag:/eIYpYzVEeay4O1JGokz2A==,type:str]
    credentials.json: ENC[AES256_GCM,data:V4wGXGyBdDMtm0PdLxis3OEUx9c7ZUT7rgr/h+/LqzYPVOPDVNUCezDhXa0/x/MrtaEQyolvSr/41RZL0pMwEexMM/vMH5biK54f421sbL8shM0MZttB6NwnUClXvjhe1qfoHEbIUCpntif69GMMGOOBqvi17s89eraWbzP4s98t64V9NnHpVBZYD5WdLJBK31UdQAVOojvIhOlgy/FcH3LlJU74QcS8pEQdgoC6Jg==,iv:RksMgje4KL0CKZJZNS6/JDwXVeQdyi7VpGs5hycFm6A=,tag:5RDCwRX6rwnJJmOzml+uTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1huwtfh57f93ceeav3k9xdmmnj90yzdaa05szskg2hat2rrq00yesyl2y5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bjdlSVRFY3doZEdUbU9t
            MDNSQUE5am5lYVovbEVlUVQwMDZnZFVCQ21FCkhYaEFiWFRTelBYdzQwOEZvK0h1
            NW5NK3lMNitKcHB2N2ZMTjhTQkFVMVEKLS0tIFJ6b1BSY1poMmE1ODRlbGVGczlk
            eGhJSitIYTZkckxVTDZQYzRwa2todG8KTLaU3gW7XiFBMEMGGHErbbmkIOxnf10q
            QMxhN7eQQKWn59ic0hMhljxig/Nq97KDiG4XQBMYi6G49n+YMT0zdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-24T22:56:09Z"
    mac: ENC[AES256_GCM,data:gxWecqrf/YfjGXhUhURvIyNWBV3+ruM85vlYn1dfSEV2HVvDRTX+obakY2faiMbTq9K83Xc6sskJRviYBXbcj4PSWTg8L0KRaqWqaAien0U0rI2qFfa72ilWoeuliOHOTA+e7veu79SlwSN7MBV/3cPbKSNGeQhJcthFygAIIdk=,iv:nP0cSBZnPGMFg605LiQTWPffcR2xk1s9yPCMNdfbKRs=,tag:uY/JeW1XxpkuN/Nwyb7Stw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
