---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittools-tagging
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent

  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "@hourly"

    restartPolicy: OnFailure

    image:
      repository: ghcr.io/buroa/qbittools
      tag: v0.9.3@sha256:98d5443a744dca1f2a3e6df8d6ab9ca7e0b7a3f0c26180319481b784cc005e31

    args:
      - tagging
      - --not-working
      - --unregistered
      - --added-on
      - --last-activity
      - --tracker-down
      - -s
      - qbittorrent.downloads.svc.cluster.local
      - -p
      - "8080"

    service:
      main:
        enabled: false

    podSecurityContext:
      runAsUser: 1030
      runAsGroup: 100

    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
