---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: obsidian-couchdb-secret
    creationPolicy: Owner
  data:
    - secretKey: couchdb-user
      remoteRef:
        key: &key bc0836b4-2e4f-42f7-85f0-b0198c99498e
        property: username
    - secretKey: couchdb-password
      remoteRef:
        key: *key
        property: password
