---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: obsidian-couchdb
  namespace: databases
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: public.ecr.aws/docker/library/couchdb
      tag: 3.3.3

    initContainers:
      init-config:
        image: busybox:latest@sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966
        command:
          - "sh"
          - "-c"
          - "cp /tmp/config/*.ini /default.d/; ls -lrt /default.d;"
        volumeMounts:
          - name: config
            mountPath: /tmp/config
          - name: config-storage
            mountPath: /default.d

    env:
      COUCHDB_USER:
        valueFrom:
          secretKeyRef:
            name: obsidian-couchdb-secret
            key: couchdb-user
      COUCHDB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: obsidian-couchdb-secret
            key: couchdb-password

    service:
      main:
        ports:
          http:
            port: 5984

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: "mdi:note-outline"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "obsidian-db.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-couchdb-configmap
        mountPath: "-"

      config-storage:
        enabled: true
        type: emptyDir
        mountPath: /opt/couchdb/etc/default.d

    volumeClaimTemplates:
      - name: data
        mountPath: /opt/couchdb/data
        accessMode: ReadWriteOnce
        size: 1Gi

    resources:
      requests:
        cpu: 34m
        memory: 127M
      limits:
        memory: 325M
