---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.14
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      serviceMonitor:
        enabled: true
        interval: 1m
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          memory: 318M
    certController:
      serviceMonitor:
        enabled: true
        interval: 1m
      resources:
        requests:
          cpu: 10m
          memory: 109M
        limits:
          memory: 550M
    resources:
      requests:
        cpu: 22m
        memory: 144M
      limits:
        memory: 724M
