---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: '{{ index . "jwt-secret" }}'
        TYPESENSE_API_KEY: '{{ index . "typesense-api-key" }}'

  data:
    - secretKey: jwt-secret
      remoteRef:
        key: &key d9ae0d9a-aff8-4f3a-8de2-3dd319749a65
        property: jwt-secret
    - secretKey: typesense-api-key
      remoteRef:
        key: *key
        property: typesense-api-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-s3
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: immich-s3-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_ACCESS_KEY: "{{ .minio_postgres_access_key }}"
        S3_SECRET_KEY: "{{ .minio_postgres_secret_key }}"
  data:
    - secretKey: minio_postgres_access_key
      remoteRef:
        key: &s3-key 6d3f7d5f-70cb-428f-8024-1dcd245d25dc
        property: username
    - secretKey: minio_postgres_secret_key
      remoteRef:
        key: *s3-key
        property: password
