---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: photos
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos
spec:
  storageClassName: photos
  capacity:
    storage: 1Mi # doesn't matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${SECRET_NAS_HOST}"
    path: "${SECRET_PHOTOS_PATH}"
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: photos
  resources:
    requests:
      storage: 1Mi # doesn't matter
