---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m

  values:
    grafana:
      enabled: true
      annotations:
        grafana_folder: Kyverno

    backgroundController:
      serviceMonitor:
        enabled: true

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - "external-secrets.io"
              resources:
                - externalsecrets
              verbs:
                - update
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - update

    cleanupController:
      serviceMonitor:
        enabled: true

    reportsController:
      serviceMonitor:
        enabled: true

    admissionController:
      serviceMonitor:
        enabled: true

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - "external-secrets.io"
              resources:
                - externalsecrets
              verbs:
                - update
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - update
