---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m

  values:
    grafana:
      enabled: true
      annotations:
        grafana_folder: Kyverno

    backgroundController:
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 109M
        limits:
          memory: 554M

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - "external-secrets.io"
              resources:
                - externalsecrets
              verbs:
                - update
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - update

    cleanupController:
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          memory: 321M

    reportsController:
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 78M
        limits:
          memory: 395M

    admissionController:
      serviceMonitor:
        enabled: true
      resources:
      requests:
        cpu: 34m
        memory: 349M

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - "external-secrets.io"
              resources:
                - externalsecrets
              verbs:
                - update
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - update
