---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tf-controller
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/flux-system/tf-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
