---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-cli
  namespace: flux-system
spec:
  target:
    name: tf-cli-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        terraform.tfrc: |-
          credentials "app.terraform.io" {
            token = "{{ .terraform_cloud_token }}"
          }
  data:
    - secretKey: terraform_cloud_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 00e3cf34-45f6-4349-9ab2-8e2762799ac8
        property: cloud-token
