---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    installCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m

    runner:
      image:
        repository: ghcr.io/arthurgeek/tf-runner-bitwarden
        tag: sha-694356bc68fa2f7081ada8649c96e71fb2189142

    resources:
      requests:
        cpu: 10m
        memory: 145M
      limits:
        memory: 376M
